project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from techy_software.views import index

admin.autodiscover()
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('techy_software/', include('techy_software.urls', namespace='techy_software')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

techy_software/urls.py
from django.urls import path
from .views import *
# from techy_software import views

app_name = 'techy_software'
urlpatterns = [
    path('', index, name='index'),
    path('saveFeedback/', saveFeedback, name="saveFeedback"),
    path('subscribe/', subscribe, name="subscribe"),
    path('NoInformationAvailable', no_info, name="no_info"),
]

techy_software/models.py
from django.db import models

# Create your models here.

class Service(models.Model):
    icon = models.ImageField()
    heading = models.TextField(default="No heading available")
    content = models.TextField(default="No content available")

    def __str__(self):
        return self.heading

class Portfolio(models.Model):
    image = models.ImageField()
    type = models.TextField(default="Not available")
    heading = models.TextField(default="No heading available")

    def __str__(self):
        return self.heading

class Feedback(models.Model):
    content = models.TextField(default="No content available")
    image = models.ImageField()
    name = models.TextField(default="No name available")
    country = models.TextField(default="No country available")

    def __str__(self):
        return self.name

class Blog(models.Model):
    image = models.ImageField()
    author = models.TextField(default="No author available")
    date = models.DateField()
    heading = models.TextField(default="No heading available")
    content = models.TextField(default="No content available")

    def __str__(self):
        return self.heading
    
class Team(models.Model):
    image = models.ImageField()
    name = models.TextField()
    
    def __str__(self):
        return self.name
  
class SaveFeedback(models.Model):
    name=models.CharField(max_length=50)
    email=models.EmailField()
    message=models.TextField()
    
    def __str__(self):
        return self.name
    
class Subscribe(models.Model):
    email=models.EmailField()
    
    def __str__(self):
        return self.email
    

techy_software/views.py
from django.shortcuts import render, redirect
from .models import *
from django.contrib import messages
# Create your views here.
services = Service.objects.all()
portfolios = Portfolio.objects.all()
feedbacks = Feedback.objects.all()
blogs = Blog.objects.all()
team = Team.objects.all()

context = {
        'services': services,
        'portfolios': portfolios,
        'feedbacks': feedbacks,
        'blogs': blogs,
        'team':team
    } 
def index(request):
    return render(request, 'index.html', context)

def saveFeedback(request):
    if request.method=='POST':
        name=request.POST.get('name')
        email=request.POST.get('email')
        message=request.POST.get('message')
        feedbackform=SaveFeedback(name=name,email=email,message=message)
        feedbackform.save()
        messages.success(request,"Feedback Submitted Successfully")
    return render(request, 'index.html', context)

def subscribe(request):
    if request.method=='POST':
        email=request.POST.get('email')
        subscribe=Subscribe(email=email)
        subscribe.save()
        messages.success(request,"Subscribed Successfully")
    return render(request, 'index.html', context) 

def no_info(request):
      return render(request, 'no_info.html')

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Techy Software</title>
    <meta name="description" content="Techy Software crafts innovative solutions, blending expertise with cutting-edge technology. Elevate your digital experience with our tailored software solutions and services.">
    <meta name="keywords" content="Techy Software, IT Solutions, Business Services, Web Development, App Development, SEO Optimization">
    <meta name="author" content="Mahin Hussain">
    <meta property="og:title" content="Techy Software">
    <meta property="og:description" content="Techy Software crafts innovative solutions, blending expertise with cutting-edge technology. Elevate your digital experience with our tailored software solutions and services.">
    <meta property="og:image" content="{% static 'images/hero.png' %}">
    <meta property="og:url" content="URL to your website">

    <link rel="icon" href="{% static "images/logo.png" %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    {% for msg in messages %}
    <div class="alert alert-warning" id="myAlert" role="alert" style="z-index:9">
        {{msg}}
      </div>
    {% endfor %}
    <section class="hero" id="hero">
        <div class="header">
         <div>
            <img src="{% static "images/logo.png" %}" alt="TECHY SOFTWARE" style="height: 80px;">
         </div>
        <div class="links">
            <a href="#hero">Home</a>
            <a href="#about">About</a>
            <a href="#portfolio">Portfolio</a>
            <a href="#testimonial">Testimonial</a>
            <a href="#team">Team</a>
            <a href="#blog">Blog</a>
            <a href="#feedback">Feedback</a>
        </div>
        <div>
            <a id="no" href="#feedback"><button >Support</button></a>
        </div>
    </div>
    
    <div class="header_small">
        <nav class="navbar navbar-expand-lg" style="background-color: white;">
            <div class="container-fluid">
                <a class="navbar-brand" href="#"><img src="{% static "images/logo.png" %}" alt="TECHY SOFTWARE" style="height: 100px;"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                    <ul class="navbar-nav">
                        <a href="#hero">Home</a>
                        <a href="#about">About</a>
                        <a href="#portfolio">Portfolio</a>
                        <a href="#testimonial">Testimonial</a>
                        <a href="#team">Team</a>
                        <a href="#blog">Blog</a>
                        <a href="#feedback">Feedback</a>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <hr>
    <div class="hero_setion">
        <div class="details">
            <div class="social_media">
                <a href="https://www.linkedin.com/"><i class="fa-brands fa-linkedin fa-2xl"></i></a>
                <a href="https://www.facebook.com/"><i class="fa-brands fa-facebook fa-2xl"></i></a>
                <a href="https://www.instagram.com/"><i class="fa-brands fa-instagram fa-2xl"></i></a>
                <a href="https://twitter.com/"><i class="fa-brands fa-twitter fa-2xl"></i></a>
            </div>
            <h1>IT Solutions & Business Services Company</h1> 
            <p>Techy Software crafts innovative solutions, blending expertise with cutting-edge technology. Elevate your digital experience with our tailored software solutions and services.</p>
            <a id="no" href="#about"><button>Our Services</button></a>
            <a id="no" href="#feedback"><button>Contact Us</button></a>
        </div>
        <div>
            <img src="{% static "images/hero.png" %}" alt="techy" class="hero_img">
        </div>
    </div>
       <img src="{% static "images/wave.png" %}" alt="">
    </section><br>
    
    <section class="about" id="about">
        <h6>What WE PROVIDE</h6>
        <h2>Our Services</h2>
        <div class="card_container">
            {% for service in services %}
        <div class="card dark">
            <img src="{{ service.icon.url }}" alt="{{ service.heading }}" style="width:100px"><br>
            <h3>{{service.heading}}</h3><br>
            <p>{{service.content}}</p>
            <a href="{% url 'techy_software:no_info' %}"><i class="fa-solid fa-arrow-right" style="color: #7b6bee;">Read More</i></a>
        </div>
        {% endfor %}
    </div>
    </section><br>
    
    <section class="portfolio" id="portfolio" style="background-color: #f7f8f8;">
        <h6>RECENT WORKS</h6>
        <h2>Our Portfolio</h2>
        <div class="buttons">
            <button id="All" class="toggler_btn" onclick="filterPortfolio(this)">All</button>
            <button id="Branding" class="off toggler_btn" onclick="filterPortfolio(this)">Branding</button>
            <button id="Application" class="off toggler_btn" onclick="filterPortfolio(this)">Application</button>
            <button id="Web_Design" class="off toggler_btn" onclick="filterPortfolio(this)">Web Design</button>
            <button id="Photography" class="off toggler_btn" onclick="filterPortfolio(this)">Photography</button>
        </div>
        <div class="portfolio_container">
            {% for portfolio in portfolios %}
            <div class="card1" data-type="{{ portfolio.type }}">
                <img src="{{ portfolio.image.url }}" alt="{{ portfolio.heading }}" class="portfolio_img" style="width:98%;top: 50%;left: 50%;"><br>
                <p class="toggler" style="display:none;">{{ portfolio.type }}</p>
            </div>
            {% endfor %}
        </div>
    </section><br>

    <section class="testimonial" id="testimonial">
        <h6>OUR TESTIMONIAL</h6>
        <h2>Client Feedback</h2>
        <div class="testimonial_container">
            {% for feedback in feedbacks %}
            <div class="card testimonial_card dark">
                <p class="star"><span><i class="fa fa-star"></i></span><span><i class="fa fa-star"></i></span><span><i class="fa fa-star"></i></span><span><i class="fa fa-star"></i></span><span><i class="fa fa-star"></i></span></p><br>
                <p>{{feedback.content}}</p>
                <img src="{{ feedback.image.url }}" alt="{{feedback.name}}"style="border-radius:50%;"><br>
                <h3>{{feedback.name}}</h3>
                <p style="color: #7b68ee;">{{feedback.country}}</p>
            </div>
            {% endfor %}
        </div>
    </section><br>

    <section class="team" id="team" style="background-color: #f7f8f8;">
        <h6>TEAM MEMBER</h6>
        <h2>Expert Team</h2>
        <div class="team_container">
            {% for team in team %}
            <div class="card">
                <img src="{{team.image.url}}" alt="{{team.name}}"><br>
                <h3 style="text-align:center;color:#7b68ee;">{{team.name}}</h3>
            </div>
            {% endfor %}
        </div>
    </section><br>
    
    <section class="blog" id="blog">
        <h6>BLOG & ARTICLE</h6>
        <h2>Recent Blog</h2>
        <div class="blog_container">
            {% for blog in blogs %}
            <div class="card dark">
                <img src="{{blog.image.url}}" alt="{{blog.author}}"><br>
                <p><span><i class="fa-regular fa-face-smile" style="color: #7b6bee;margin-left:10px;margin-right:5px;"></i>{{blog.author}}</span>
                <span><i class="fa-solid fa-calendar-days" style="color: #7b68ee;margin-left:10px;margin-right:5px;"></i>{{blog.date}}</span></p>
                <h3>{{blog.heading}}</h3><br>
                <p>{{blog.content}}</p>
                <a href="{% url 'techy_software:no_info' %}"><i class="fa-solid fa-arrow-right" style="color: #7b6bee;">Read More</i></a>
            </div>
            {% endfor %}
        </div>
    </section><br>

    <section class="feedback dark" id="feedback">
        <h3 style="text-align: center; color: #7b68ee;">Feedback: Share, Shape, Improve.</h3>
        <div class="feedback_details">
        <div class="contact_info">
            <h3>Contact Info</h3>
            <p><i class="fa-solid fa-envelope"></i>
            <b>Email</b><br>xyz@abc.com</p>
            <p><i class="fa-solid fa-phone"></i>
            <b>Phone</b><br>123-456-789</p>
            <p><i class="fa-solid fa-location-dot"></i>
            <b>Address</b><br>
            123 Abcd Street, XYZ, PQRS</p>
        </div>
        <br> 
        <div>  
        <form method="post" action="{% url 'techy_software:saveFeedback' %}" class="feedback_form">
            {% csrf_token %}
            <div class="form_part">
            <input type="name" id="name" name="name" placeholder="Name" class="input" required>
            <input type="email" id="email" name="email" placeholder="Email" class="input" required><br>
        </div>
            <textarea rows="4" cols="30" name="message" placeholder="Message"></textarea><br>
            <button type="submit">Submit</button>
        </form>
    </div>
</div>
    </section><br>

    <footer>
        <div class="newsletter">
            <div>
                <h3>Sign Up Our Newsletter</h3>
                <p>We Offer An Informative Monthly Technology Newsletter<br>- Check It Out.</p>
            </div>
            <div>
                <form action={% url "techy_software:subscribe" %} method="post">
                    {% csrf_token %}
                    <input type="email" id="email" name="email" placeholder="Enter your email" class="input" required>
                    <button type="submit">Subscribe</button>
                </form>
            </div>
        </div>
        <hr>
        <div class="info">
            <div class="techy">
                <h2><img src="{% static "images/logo.png" %}" alt="TECHY SOFTWARE" style="height: 50px; ">Techy Software</h2>
                <p>Techy Software crafts innovative solutions, blending expertise with cutting-edge technology. Elevate your digital experience with our tailored software solutions and services.</p>
                <div class="social_media">
                    <a href="https://www.linkedin.com/"><i class="fa-brands fa-linkedin fa-2xl"></i></a>
                    <a href="https://www.facebook.com/"><i class="fa-brands fa-facebook fa-2xl"></i></a>
                    <a href="https://www.instagram.com/"><i class="fa-brands fa-instagram fa-2xl"></i></a>
                    <a href="https://twitter.com/"><i class="fa-brands fa-twitter fa-2xl"></i></a>
                </div>
            </div>
            <div class="our_services">
                <h3>Our Services</h3>
                <a href="{% url 'techy_software:no_info' %}">Startup Solutions</a><br>
                <a href="{% url 'techy_software:no_info' %}">Web Devlopment</a><br>
                <a href="{% url 'techy_software:no_info' %}">Apps Devlopment</a><br>
                <a href="{% url 'techy_software:no_info' %}">Networking Services</a><br>
                <a href="{% url 'techy_software:no_info' %}">SEO Optimisation</a><br>
            </div>
            <div class="useful_links">
                <h3>Useful Links</h3>
                <a href="{% url 'techy_software:no_info' %}">About Us</a><br>
                <a href="{% url 'techy_software:no_info' %}">Case Study</a><br>
                <a href="{% url 'techy_software:no_info' %}">Contact Info</a><br>
                <a href="{% url 'techy_software:no_info' %}">Privacy Policy</a><br>
                <a href="{% url 'techy_software:no_info' %}">Terms & Conditions</a><br>
            </div>
        </div>
        <hr>
        <div class="copyrights">
            <div>© 2024 Techy Software - All Rights Reserved.</div>
            <div class="footer_dets"><a href="{% url 'techy_software:no_info' %}">Terms & Conditions </a>| <a href="{% url 'techy_software:no_info' %}">Privacy Policy</a>
            </div>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="{% static 'script.js' %}"></script>
</body>
</html>

templates/no_info.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static "images/logo.png" %}" type="image/x-icon">
    <title>No Information Available</title>
</head>
<body>
    <h2>No Information Available</h2><br>
    <p>*Will be updated soon</p>
</body>
</html>